# Generated by Django 4.1.7 on 2023-03-14 14:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("menu", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="CategoriaCibo",
            new_name="CategoriaDiCibo",
        ),
    ]
